---
- name: Create EKS Cluster Role
  amazon.aws.iam_role:
    name: "eks-cluster-role-{{ environment }}"
    description: "IAM role for EKS cluster"
    assume_role_policy:
      Version: "2012-10-17"
      Statement:
        - Effect: "Allow"
          Principal:
            Service: "eks.amazonaws.com"
          Action: "sts:AssumeRole"
    managed_policies: "{{ eks_cluster_managed_policies }}"
    tags:
      Environment: "{{ environment }}"
  register: eks_cluster_role

- name: Create EKS Node Group Role
  amazon.aws.iam_role:
    name: "eks-nodegroup-role-{{ environment }}"
    description: "IAM role for EKS worker nodes"
    assume_role_policy:
      Version: "2012-10-17"
      Statement:
        - Effect: "Allow"
          Principal:
            Service: "ec2.amazonaws.com"
          Action: "sts:AssumeRole"
    managed_policies: "{{ eks_nodegroup_managed_policies }}"
    tags:
      Environment: "{{ environment }}"
  register: eks_nodegroup_role

- name: Create ECR Access Policy
  amazon.aws.iam_policy:
    name: "eks-ecr-access-{{ environment }}"
    description: "ECR access for EKS workloads"
    policy: "{{ ecr_policy_document }}"
    tags:
      Environment: "{{ environment }}"
  register: ecr_policy

- name: Attach ECR Policy to Node Group Role
  community.aws.iam_policy:
    policy_arn: "{{ ecr_policy.policy.arn }}"
    iam_type: "role"
    iam_name: "{{ eks_nodegroup_role.role.role_name }}"
    state: "present"
