---
- name: Create EKS Cluster Role
  amazon.aws.iam_role:
    name: "eks-cluster-role-{{ environment | regex_replace('[^a-zA-Z0-9+=,.@-_]', '') }}"
    description: "IAM role for EKS cluster"
    assume_role_policy_document: "{{ eks_cluster_trust_policy | to_json }}"
    managed_policies: "{{ eks_cluster_managed_policies }}"
    tags:
      Environment: "{{ environment }}"
  register: eks_cluster_role

- name: Create EKS Node Group Role
  amazon.aws.iam_role:
    name: "eks-nodegroup-role-{{ environment | regex_replace('[^a-zA-Z0-9+=,.@-_]', '') }}"
    description: "IAM role for EKS worker nodes"
    assume_role_policy_document: "{{ eks_nodegroup_trust_policy | to_json }}"
    managed_policies: "{{ eks_nodegroup_managed_policies }}"
    tags:
      Environment: "{{ environment }}"
  register: eks_nodegroup_role

- name: Create ECR Access Policy
  amazon.aws.iam_policy:
    name: "eks-ecr-access-{{ environment | regex_replace('[^a-zA-Z0-9+=,.@-_]', '') }}"
    description: "ECR access for EKS workloads"
    policy_document: "{{ ecr_policy_document | to_json }}"
    tags:
      Environment: "{{ environment }}"
  register: ecr_policy

- name: Attach ECR Policy to Node Group Role
  community.aws.iam_policy:
    policy_arn: "{{ ecr_policy.policy.arn }}"
    iam_type: "role"
    iam_name: "{{ eks_nodegroup_role.role.role_name }}"
    state: "present"
