---
- name: Create EKS Cluster Role
  amazon.aws.iam_role:
    name: "eks-cluster-role"
    description: "IAM role for EKS cluster"
    assume_role_policy_document: "{{ eks_cluster_trust_policy | to_json }}"
    managed_policies: "{{ eks_cluster_managed_policies }}"
    tags:
      Environment: "{{ env_name }}"
  register: eks_cluster_role

- name: Create EKS Node Group Role
  amazon.aws.iam_role:
    name: "eks-nodegroup-role"
    description: "IAM role for EKS worker nodes"
    assume_role_policy_document: "{{ eks_nodegroup_trust_policy | to_json }}"
    managed_policies: "{{ eks_nodegroup_managed_policies }}"
    tags:
      Environment: "{{ env_name }}"
  register: eks_nodegroup_role
