---
- name: Cleanup AWS Infrastructure
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Include cleanup tasks
      ansible.builtin.include_role:
        name: vpc
        tasks_from: cleanup.yml
