---
- name: Basic Infrastructure Tests
  hosts: localhost
  gather_facts: false
  vars_files:
    - group_vars/all.yml
  collections:
    - amazon.aws

  tasks:
    - name: Test VPC exists
      amazon.aws.ec2_vpc_net_info:
        filters:
          "tag:Environment": "{{ env_name }}"
        region: "{{ aws_region }}"
      register: vpc_info

    - name: Test EKS cluster exists
      community.aws.eks_cluster:
        name: "{{ eks_cluster_name }}"
        region: "{{ aws_region }}"
        state: present
      register: eks_info
      ignore_errors: true

    - name: Show test results
      debug:
        msg: |
          🧪 Infrastructure Test Results:
          ✅ VPC: {{ 'PASS' if vpc_info.vpcs | length > 0 else 'FAIL' }}
          ✅ EKS: {{ 'PASS' if eks_info.cluster is defined else 'FAIL' }}
          
          {% if vpc_info.vpcs | length > 0 %}
          📋 VPC ID: {{ vpc_info.vpcs[0].id }}
          {% endif %}
          {% if eks_info.cluster is defined %}
          📋 EKS Cluster: {{ eks_info.cluster.name }} ({{ eks_info.cluster.status }})
          {% endif %}
