---
- name: Basic Infrastructure Tests
  hosts: localhost
  gather_facts: false
  collections:
    - amazon.aws

  tasks:
    - name: Test VPC exists
      amazon.aws.ec2_vpc_net_info:
        filters:
          "tag:Environment": "{{ environment }}"
        region: "{{ aws_region }}"
      register: vpc_info

    - name: Show VPC Test Result
      debug:
        msg: "✅ VPC test passed: {{ vpc_info.vpcs[0].id }}"
      when: vpc_info.vpcs | length > 0

    - name: Show VPC Test Failure
      debug:
        msg: "❌ VPC test failed: No VPC found for environment {{ environment }}"
      when: vpc_info.vpcs | length == 0
