---
# Default vars for EKS role (used by eksctl)

aws_region: "us-east-2"
env_name: "uat-edfx"
eks_version: "1.30"

# Nodegroup defaults
nodegroup_instance_types: ["t3.medium"]
nodegroup_desired_size: 2
nodegroup_min_size: 1
nodegroup_max_size: 3
nodegroup_disk_size: 20

# Cluster default tags
eks_cluster_tags:
  Environment: "{{ env_name }}"
  ManagedBy: "ansible"
  Project: "ansible-cicd"
