---
aws_region: us-east-2

# ====== Cluster Configuration ======
eks_version: "1.30" # Ensure supported version
eks_cluster_name: "eks-{{ env_name }}"
endpoint_public_access: true
endpoint_private_access: true
public_access_cidrs:
  - "0.0.0.0/0" # restrict later in production

cluster_logging:
  clusterLogging:
    - types: ["api", "audit", "authenticator", "controllerManager", "scheduler"]
      enabled: true

eks_cluster_tags:
  Environment: "{{ env_name }}"
  Name: "eks-{{ env_name }}"
  ManagedBy: "ansible"
  Project: "ansible-cicd"

# ====== Nodegroup Configuration ======
nodegroup_name: "ng-{{ env_name }}"
nodegroup_instance_types: ["t3.medium"]
nodegroup_desired_size: 2
nodegroup_min_size: 1
nodegroup_max_size: 3
nodegroup_disk_size: 20
nodegroup_ami_type: "AL2_x86_64"
nodegroup_capacity_type: "ON_DEMAND"
nodegroup_labels: {}
nodegroup_taints: []

nodegroup_tags:
  Environment: "{{ env_name }}"
  Name: "ng-{{ env_name }}"
  ManagedBy: "ansible"
  Project: "ansible-cicd"

# ====== Timeouts ======
cluster_create_timeout: 1800 # 30 min
nodegroup_create_timeout: 3600 # 60 min
