---
# AWS Region
aws_region: "us-east-2"

# VPC CIDR (needed for worker node security group rules)
vpc_cidr: "10.0.0.0/16"

# Security Group Configuration
eks_controlplane_sg_name: "eks-controlplane-{{ env_name }}"
eks_workernodes_sg_name: "eks-workernodes-{{ env_name }}"

# Security Group Rules - Control Plane
control_plane_rules:
  - proto: tcp
    ports:
      - 443
    cidr_ip: "0.0.0.0/0"
    rule_desc: "Allow Kubernetes API access"

# Security Group Rules - Worker Nodes
workernodes_rules:
  - proto: all
    rule_desc: "Allow all traffic from Control Plane"
    # group_id will be set dynamically
  - proto: all
    rule_desc: "Allow all traffic between worker nodes"
    self: true
  - proto: tcp
    from_port: 1025
    to_port: 65535
    cidr_ip: "{{ vpc_cidr }}"
    rule_desc: "Allow NodePort services"
  - proto: tcp
    from_port: 443
    to_port: 443
    cidr_ip: "0.0.0.0/0"
    rule_desc: "Allow HTTPS"
  - proto: tcp
    from_port: 80
    to_port: 80
    cidr_ip: "0.0.0.0/0"
    rule_desc: "Allow HTTP"
