---
aws_region: us-east-2
env_name: uat-edfx # will be overridden by your playbook
vpc_cidr: "10.0.0.0/16"

# SG names derived only from env_name
eks_controlplane_sg_name: "eks-controlplane-{{ env_name }}"
eks_workernodes_sg_name: "eks-workernodes-{{ env_name }}"

# Control-plane rules (tune as needed)
control_plane_rules:
  - proto: tcp
    ports: [443]
    cidr_ip: "0.0.0.0/0"
    rule_desc: "Allow EKS API (HTTPS) — adjust as needed"
  - proto: all
    cidr_ip: "{{ vpc_cidr }}"
    rule_desc: "Allow all traffic within VPC"
