---
# ────────────────────────────────────────────────
# Environment and Region Settings
# ────────────────────────────────────────────────
aws_region: "us-east-1"

# ────────────────────────────────────────────────
# Security Group Naming
# ────────────────────────────────────────────────
eks_controlplane_sg_name: "eks-controlplane-{{ env_name }}"
eks_workernodes_sg_name: "eks-workernodes-{{ env_name }}"

# ────────────────────────────────────────────────
# Control Plane SG Rules
# ────────────────────────────────────────────────
control_plane_rules:
  - proto: tcp
    ports: [443]
    cidr_ip: "0.0.0.0/0"
    rule_desc: "Allow Kubernetes API Access"
  - proto: tcp
    ports: [80]
    cidr_ip: "0.0.0.0/0"
    rule_desc: "Allow HTTP (Optional for Ingress or Health Checks)"

# ────────────────────────────────────────────────
# Default Worker Node Rules Template
# (Will be dynamically updated at runtime)
# ────────────────────────────────────────────────
workernodes_rules: []
