---
- name: Get VPC information by tags
  amazon.aws.ec2_vpc_net_info:
    region: "{{ aws_region }}"
    filters:
      "tag:Environment": "{{ env_name }}"
      "tag:ManagedBy": "ansible"
  register: vpc_info

- name: Fail if VPC not found
  fail:
    msg: "VPC with Environment tag '{{ env_name }}' not found. Run VPC role first."
  when: vpc_info.vpcs | length == 0

- name: Set VPC ID
  set_fact:
    vpc_id: "{{ vpc_info.vpcs[0].id }}"

# --- Create Control Plane SG ---
- name: Create EKS Control Plane Security Group
  amazon.aws.ec2_security_group:
    name: "{{ eks_controlplane_sg_name }}"
    description: "EKS Control Plane Security Group"
    vpc_id: "{{ vpc_id }}"
    region: "{{ aws_region }}"
    rules: "{{ control_plane_rules }}"
    tags:
      Name: "{{ eks_controlplane_sg_name }}"
      Environment: "{{ env_name }}"
      ManagedBy: "ansible"
  register: eks_controlplane_sg

# --- Build Worker Node Rules Dynamically ---
- name: Build worker node rules list dynamically
  set_fact:
    workernodes_rules:
      - proto: all
        group_id: "{{ eks_controlplane_sg.group_id }}"
        rule_desc: "Allow all traffic from Control Plane"
      - proto: all
        self: true
        rule_desc: "Allow all traffic between worker nodes"
      - proto: tcp
        ports: [1025, 65535]
        cidr_ip: "{{ vpc_info.vpcs[0].cidr_block }}"
        rule_desc: "Allow NodePort services"
      - proto: tcp
        ports: [443]
        cidr_ip: "0.0.0.0/0"
        rule_desc: "Allow HTTPS"
      - proto: tcp
        ports: [80]
        cidr_ip: "0.0.0.0/0"
        rule_desc: "Allow HTTP"

# --- Create Worker Node SG ---
- name: Create EKS Worker Node Security Group
  amazon.aws.ec2_security_group:
    name: "{{ eks_workernodes_sg_name }}"
    description: "EKS Worker Nodes Security Group"
    vpc_id: "{{ vpc_id }}"
    region: "{{ aws_region }}"
    rules: "{{ workernodes_rules }}"
    tags:
      Name: "{{ eks_workernodes_sg_name }}"
      Environment: "{{ env_name }}"
      ManagedBy: "ansible"
  register: eks_workernodes_sg

# --- Debug Output ---
- name: Debug created security groups
  debug:
    msg:
      - "Control Plane SG: {{ eks_controlplane_sg.group_id }}"
      - "Worker Nodes SG: {{ eks_workernodes_sg.group_id }}"
