---
# 1) Discover VPC by tags
- name: Get VPC information by tags
  amazon.aws.ec2_vpc_net_info:
    region: "{{ aws_region }}"
    filters:
      "tag:Environment": "{{ env_name }}"
      "tag:ManagedBy": "ansible"
  register: vpc_info

- name: Fail if VPC not found
  fail:
    msg: "VPC with Environment tag '{{ env_name }}' not found. Run VPC role first."
  when: vpc_info.vpcs | length == 0

- name: Set VPC ID
  set_fact:
    vpc_id: "{{ vpc_info.vpcs[0].id }}"

# 2) Control Plane SG
- name: Create EKS Control Plane Security Group
  amazon.aws.ec2_security_group:
    name: "{{ eks_controlplane_sg_name }}"
    description: "EKS Control Plane Security Group"
    vpc_id: "{{ vpc_id }}"
    region: "{{ aws_region }}"
    purge_rules: no
    rules: "{{ control_plane_rules }}"
    tags:
      Name: "{{ eks_controlplane_sg_name }}"
      Environment: "{{ env_name }}"
      ManagedBy: "ansible"
  register: eks_controlplane_sg

# 3) Worker SG (base rules first)
- name: Create EKS Worker Node Security Group (base)
  amazon.aws.ec2_security_group:
    name: "{{ eks_workernodes_sg_name }}"
    description: "EKS Worker Nodes Security Group"
    vpc_id: "{{ vpc_id }}"
    region: "{{ aws_region }}"
    purge_rules: no
    rules:
      - proto: all
        group_id: "{{ eks_controlplane_sg.group_id }}"
        rule_desc: "Allow all from control plane"
      - proto: tcp
        from_port: 30000
        to_port: 32767
        cidr_ip: "{{ vpc_cidr }}"
        rule_desc: "K8s NodePort range"
      - proto: tcp
        ports: [443]
        cidr_ip: "0.0.0.0/0"
        rule_desc: "HTTPS"
      - proto: tcp
        ports: [80]
        cidr_ip: "0.0.0.0/0"
        rule_desc: "HTTP"
    tags:
      Name: "{{ eks_workernodes_sg_name }}"
      Environment: "{{ env_name }}"
      ManagedBy: "ansible"
  register: eks_workernodes_sg

# 4) Wait for eventual consistency
- name: Wait until worker SG is discoverable
  amazon.aws.ec2_security_group_info:
    region: "{{ aws_region }}"
    filters:
      group-id: "{{ eks_workernodes_sg.group_id }}"
  register: sg_lookup
  retries: 6
  delay: 5
  until: sg_lookup.security_groups | length > 0

# 5) Append self-referencing rule
- name: Allow all between worker nodes (self)
  amazon.aws.ec2_security_group:
    group_id: "{{ eks_workernodes_sg.group_id }}"
    name: "{{ eks_workernodes_sg_name }}" # required when state=present
    description: "EKS Worker Nodes Security Group" # required when state=present
    vpc_id: "{{ vpc_id }}"
    region: "{{ aws_region }}"
    purge_rules: no
    rules:
      - proto: all
        group_id: "{{ eks_workernodes_sg.group_id }}"
        rule_desc: "Allow all between worker nodes"

# 6) Debug
- name: Debug created security groups
  debug:
    msg:
      - "Control Plane SG: {{ eks_controlplane_sg.group_id }}"
      - "Worker Nodes SG: {{ eks_workernodes_sg.group_id }}"
