---
- name: Get VPC by environment tag
  amazon.aws.ec2_vpc_net_info:
    filters:
      "tag:Environment": "{{ environment }}"
    region: "{{ aws_region }}"
  register: vpc_info

- name: Delete VPC and dependencies
  amazon.aws.ec2_vpc_net:
    vpc_id: "{{ item.id }}"
    state: absent
    region: "{{ aws_region }}"
  loop: "{{ vpc_info.vpcs }}"
  when: vpc_info.vpcs | length > 0
